### PR TITLE
Fix paused timer

### PR DESCRIPTION
**Pull request by xseignard**

### CODE REVIEW

**Comment by xseignard** [comment]
According to #1 it should fix the problem, but not for me.

Any idea?

**Comment by AndrewMascolo** [comment]
It should look like this.

 

boolean Timer()

               {

                 static unsigned long duration = 1000000; // 1 second

                 timeFlag = false;

                 if (!Stop && !Paused) // if not Stopped or Paused, run timer

                 {

                              if ((_micro = micros()) - time > duration ) // check the time difference and see if 1 second has elapsed

                              {

                                Clock--;

                                timeFlag = true;

 

                                if (Clock == 0) // check to see if the clock is 0

                                             Stop = true; // If so, stop the timer

                                             

                                _micro < time ? time = _micro : time += duration; // check to see if micros() has rolled over, if not, then increment "time" by duration

                              }

                 }

                 

                 if(Paused) 

                   time += micros();

                              

                 return !Stop; // return the state of the timer

               }

**Comment by xseignard** [comment]
It works, it was a mistake of mine.

**Comment by xseignard** [comment]
I mean the fix I propose works.

**Comment by AndrewMascolo** [comment]
Which is?

**Comment by xseignard** [comment]
This PR is mandatory for the lib to work.

**Pull request closed without merging**
